### ISSUE TITLE
В чем смысл существования этого скачивателя репозиториев?

### ISSUE THREAD

**Issue by NewGrafon** [Xenely14/stalcraft-database-parser#1]
А по данной ситуации держите мем:
**git pull**: изобрели в 2005 году
Люди до 2005 года:
https://github.com/Xenely14/stalcraft-database-parser/blob/main/main.py

**Comment by Xenely14** [comment]
Данный "скачиватель" сделан для более гибкой работы с репозиторием. Мне вот, например, очень удобно загонять полученные файлы прямиком в Redis, как говорится: "Не нравится - не используй, заставлять тебя никто не будет".
